name: First Workflow
on: workflow_dispatch
jobs: 
  first_job: 
    runs-on: ubuntu-latests
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done-bye!"
      
